package com.group55.gastoflow_ca.core.enums;

public enum Permission {
    CREATE_USERTYPE,
    READ_USERTYPE,
    READ_ALL_USERTYPE,
    EDIT_USERTYPE,
    EDIT_ALL_USERTYPE,
    DELETE_USERTYPE,
    DELETE_ALL_USERTYPE,

    CREATE_USER,
    READ_USER,
    READ_ALL_USER,
    EDIT_USER,
    EDIT_ALL_USER,
    DELETE_USER,
    DELETE_ALL_USER,

    CREATE_RESTAURANT,
    READ_RESTAURANT,
    READ_ALL_RESTAURANT,
    EDIT_RESTAURANT,
    EDIT_ALL_RESTAURANT,
    DELETE_RESTAURANT,
    DELETE_ALL_RESTAURANT,

    CREATE_MENU_ITEM,
    CREATE_ALL_MENU_ITEM,
    READ_MENU_ITEM,
    READ_ALL_MENU_ITEM,
    EDIT_MENU_ITEM,
    EDIT_ALL_MENU_ITEM,
    DELETE_MENU_ITEM,
    DELETE_ALL_MENU_ITEM

}
